#pragma once

#define APP_ENV_LIVIN_ROOM 1
#define APP_ENV_BEDROOM 2
#define APP_ENV_OTHER 3

#if APP_ENV == APP_ENV_LIVIN_ROOM
#define PIN_IR_RECEIVER 2
#elif APP_ENV == APP_ENV_BEDROOM
#define PIN_IR_RECEIVER 5
#elif APP_ENV == APP_ENV_OTHER
#define PIN_IR_RECEIVER 5
#endif
