#pragma once

#define APP_DEBUG false
#define APP_DEBUG_HEAP false
#define APP_DEBUG_TEMPERATURE_CHANGE false
#define APP_DEBUG_RANDOM_TEMPERATURE_SENSOR false
#define APP_DEBUG_IR_SEND false
#define APP_DEBUG_DATABASE_TEMPERATURE_CHECK false

#define APP_REBOOT_DELAY (12 * 60 * 60 * 1000)
#define APP_DEBUG_HEAP_DELAY (10 * 1000)
#define APP_AC_CONTROL_TURN_OFF_DELAY (3 * 60 * 60 * 1000)
#define APP_AC_CONTROL_CHECK_DELAY (5 * 60 * 1000)
#define APP_TEMPERATURE_SENSOR_TEMPERATURE_DELAY (10 * 1000)
#define APP_TEMPERATURE_SENSOR_HUMIDITY_DELAY (60 * 1000)
#define APP_TEMPERATURE_SENSOR_DATABASE_DELAY (10 * 1000)
