#pragma once

#define APP_DEBUG false
#define APP_DEBUG_HEAP false
#define APP_DEBUG_TEMPERATURE_CHANGE false
#define APP_DEBUG_RANDOM_TEMPERATURE_SENSOR false
#define APP_DEBUG_IR_SEND false
#define APP_DEBUG_IR_RECEIVE false
#define APP_DEBUG_DATABASE_TEMPERATURE_CHECK false

#define APP_REBOOT_DELAY (12 * 60 * 60 * 1000)
#define APP_DEBUG_HEAP_DELAY (10 * 1000)
#define APP_AC_CONTROL_TURN_OFF_DELAY (3 * 60 * 60 * 1000)
#define APP_AC_CONTROL_CHECK_DELAY (5 * 60 * 1000)
#define APP_TEMPERATURE_SENSOR_TEMPERATURE_DELAY (10 * 1000)
#define APP_TEMPERATURE_SENSOR_HUMIDITY_DELAY (60 * 1000)
#define APP_TEMPERATURE_SENSOR_DATABASE_DELAY (10 * 1000)

#define APP_ENV_LIVIN_ROOM 1
#define APP_ENV_BEDROOM 2
#define APP_ENV_OTHER 3

#if APP_ENV == APP_ENV_LIVIN_ROOM
  #define APP_IR_RECEIVER true

  #define PIN_ONBOARD_LED GPIO_NUM_38

  #define PIN_TEMP_SENSOR GPIO_NUM_10

  #define PIN_IR_TRANSMITTER GPIO_NUM_9
  #define PIN_IR_RECEIVER GPIO_NUM_5

  #define PIN_SD_SCK GPIO_NUM_36
  #define PIN_SD_MISO GPIO_NUM_37
  #define PIN_SD_MOSI GPIO_NUM_35
  #define PIN_SD_SS GPIO_NUM_39

  #define DHT_TYPE DHT22

  #include <ir_Haier.h>
  #define IR_SEND_CLASS IRHaierAC160
#elif APP_ENV == APP_ENV_BEDROOM
  #define APP_IR_RECEIVER false

  #define PIN_TEMP_SENSOR GPIO_NUM_32

  #define PIN_IR_TRANSMITTER GPIO_NUM_22
  #define PIN_IR_RECEIVER GPIO_NUM_34

  #define PIN_SD_SCK GPIO_NUM_18
  #define PIN_SD_MISO GPIO_NUM_19
  #define PIN_SD_MOSI GPIO_NUM_23
  #define PIN_SD_SS GPIO_NUM_5

  #define DHT_TYPE DHT22

  #include <ir_Haier.h>
  #define IR_SEND_CLASS IRHaierACYRW02
#elif APP_ENV == APP_ENV_OTHER
  #define APP_IR_RECEIVER true

  #define PIN_ONBOARD_LED GPIO_NUM_38

  #define PIN_TEMP_SENSOR GPIO_NUM_10

  #define PIN_IR_TRANSMITTER GPIO_NUM_9
  #define PIN_IR_RECEIVER GPIO_NUM_5

  #define PIN_SD_SCK GPIO_NUM_36
  #define PIN_SD_MISO GPIO_NUM_37
  #define PIN_SD_MOSI GPIO_NUM_35
  #define PIN_SD_SS GPIO_NUM_39

  #define DHT_TYPE DHT11

  #include <ir_Bosch.h>
  #define IR_SEND_CLASS IRBosch144AC
#endif
