#pragma once

#define DEBUG false
#define DEBUG_TEMPERATURE_CHANGE false
#define DEBUG_IR_SEND false

#define REBOOT_DELAY (12 * 60 * 60 * 1000)
#define AC_CONTROL_TURN_OFF_DELAY (3 * 60 * 60 * 1000)
#define TEMPERATURE_SENSOR_TEMPERATURE_DELAY (10 * 1000)
#define TEMPERATURE_SENSOR_HUMIDITY_DELAY (60 * 1000)
